# Generated by Django 4.0.4 on 2022-05-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='eメール')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
            ],
        ),
    ]
