version: '3'

volumes:
  nestjs-node-modules:

services:
  db:
    image: mysql:5.7
    container_name: "sampledb"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  node:
    build:
      context: .
      dockerfile: DockerfileNode
    command: sh -c "npm run dev"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./vite-project:/front:cached
      - nestjs-node-modules:/front/node_modules
    ports:
      - "3000:3000"
    depends_on: 
      - "db"
  
  django:
    build:
      context: .
      dockerfile: DockerfileDjango
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./backend:/backend:cached
    ports: 
      - "8000:8000"
    depends_on: 
      - "node"